version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./backups:/backups
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=bilal.kramdi@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

  hasura:
    image: hasura/graphql-engine:v2.36.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hasura:/hasura-project
    working_dir: /hasura-project
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    labels:
      - "traefik.enable=true"

      # Router HTTPS principal pour Hasura
      - "traefik.http.routers.hasura.rule=Host(`hasura.perftrain.com`)"
      - "traefik.http.routers.hasura.entrypoints=websecure"
      - "traefik.http.routers.hasura.tls.certresolver=myresolver"
      - "traefik.http.services.hasura.loadbalancer.server.port=8080"

      # Router HTTP pour redirection automatique vers HTTPS
      - "traefik.http.routers.hasura-http.rule=Host(`hasura.perftrain.com`)"
      - "traefik.http.routers.hasura-http.entrypoints=web"
      - "traefik.http.routers.hasura-http.middlewares=redirect-to-https"

      # Middleware de redirection HTTP â†’ HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

volumes:
  db_data:
