version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"                   # Dashboard Traefik (optionnel)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=bilal.kramdi@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  hasura:
    image: hasura/graphql-engine:v2.31.0
    container_name: hasura
    restart: unless-stopped
    ports:
      - "8080:8080"  # interne Docker
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@postgres:5432/dbname
      HASURA_GRAPHQL_ADMIN_SECRET: tonSecret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`hasura.perftrain.com`)"
      - "traefik.http.routers.hasura.entrypoints=web"
      - "traefik.http.routers.hasura.entrypoints=websecure"
      - "traefik.http.routers.hasura.tls=true"
      - "traefik.http.routers.hasura.tls.certresolver=myresolver"
      - "traefik.http.services.hasura.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
